version: '3.4'

services:
 sqldata:
  image: mcr.microsoft.com/mssql/server:2019-latest
  environment:
   - SA_PASSWORD=Pass@word
   - ACCEPT_EULA=Y
  ports:
   - "1433:1433"
  volumes:
   - tareas-sqldata:/var/opt/mssql
 tareasapi:
  image: ${DOCKER_REGISTRY-}tareasapi
  build:
   context: .
   dockerfile: TareasAPI/Dockerfile
  depends_on:
   - sqldata
  environment:
   - ASPNETCORE_ENVIRONMENT=Docker
   - ASPNETCORE_URLS=http://+:80
  ports:
   - "5000:80"
 tareasmvc:
  image: ${DOCKER_REGISTRY-}tareasmvc
  build:
   context: .
   dockerfile: TareasWeb/Dockerfile
  depends_on:
   - sqldata
   - tareasapi
  environment:
   - ASPNETCORE_ENVIRONMENT=Docker
   - ASPNETCORE_URLS=http://+:80
  ports:
   - "5002:80"
 watchdog:
  image: ${DOCKER_REGISTRY-}watchdog
  build:
   context: .
   dockerfile: WatchDog/Dockerfile
  depends_on:
   - sqldata
  environment:
   - ASPNETCORE_ENVIRONMENT=Docker
   - ASPNETCORE_URLS=http://+:80
  ports:
   - "5004:80"
volumes:
 tareas-sqldata:
  external: false