apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
  labels:
    name: seq-deployment
    env: dev
spec:
  template:
    metadata:
      name: seq
      labels:
        name: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          imagePullPolicy: IfNotPresent
  replicas: 1
  selector:
    matchLabels:
      name: seq