apiVersion: v1
kind: Service
metadata:
  name: seq-service
  labels:
    name: seq
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: ingress
      port: 5341
      targetPort: 5341
  selector:
    name: seq