apiVersion: v1
kind: Service
metadata:
  name: tareasmvc
  labels:
    name: tareasmvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    name: tareasmvc