name: Pruebas proyectos en .NET

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.416
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Copy tests results
      run: | 
        cp ./IntegrationTest/TestResults/**/coverage.cobertura.xml ./IntegrationTest/TestResults/coverage.cobertura.xml
        cp ./FunctionalTests/TestResults/**/coverage.cobertura.xml ./FunctionalTests/TestResults/coverage.cobertura.xml
        cp ./UnitTests/TestResults/**/coverage.cobertura.xml ./UnitTests/TestResults/coverage.cobertura.xml
    - name: Codecov
      uses: codecov/codecov-action@v3.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./IntegrationTest/TestResults/coverage.cobertura.xml,./FunctionalTests/TestResults/coverage.cobertura.xml,./UnitTests/TestResults/coverage.cobertura.xml # optional
        flags: unittests # optional
        name: codecov-tareas-dot-net # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

